### ISSUE TITLE
Organisation should be called Organization

### ISSUE THREAD

**Issue by kedare** [m0nhawk/grafana_api#11]
**Describe the bug**
All the references to Organization are called Organisation in the code, this is not correct.

**To Reproduce**
```
grafana = grafana_api.GrafanaFace(
    host=GRAFANA_HOST,
    auth=GRAFANA_KEY,
    protocol="https",
    port=443
)

log.debug(grafana.organization)
```

**Expected behavior**
Organization API should be returned instead of None

**Versions**
- Grafana: [ 6.0.0 ]
- `grafana_api`: [ grafana-api==0.5.2 ]
- Authentication: [Token]

**Comment by svet-b** [comment]
This change should also be applied to the other sub-modules with similarly named functions, e.g. `user` currently has `get_user_organisations()`, `switch_user_organisation()`, `switch_actual_user_organisation`, and `get_actual_user_organisations`.

Under the current situation I need to keep checking the source code for this module in order to work out whether I should be calling it "organization" or "organisation", depending on which specific function I'm calling...
